// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprRWHZ4A5gB4b3-uM3lrs8qWwBn-GtGI',
    appId: '1:69956068335:web:a82214e28a749509cc4c1a',
    messagingSenderId: '69956068335',
    projectId: 'notes-b5858',
    authDomain: 'notes-b5858.firebaseapp.com',
    storageBucket: 'notes-b5858.appspot.com',
    measurementId: 'G-RJCH8R3703',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUpXHOPalMp-2ab29BnciSGnjzBk00-88',
    appId: '1:69956068335:android:e7535d7379739d94cc4c1a',
    messagingSenderId: '69956068335',
    projectId: 'notes-b5858',
    storageBucket: 'notes-b5858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC96zIrLRaNlUwrqJNhcUA60DE1Y-IBB_s',
    appId: '1:69956068335:ios:0f41b014436a76a6cc4c1a',
    messagingSenderId: '69956068335',
    projectId: 'notes-b5858',
    storageBucket: 'notes-b5858.appspot.com',
    iosBundleId: 'com.mobileprogramming.klp5Mp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC96zIrLRaNlUwrqJNhcUA60DE1Y-IBB_s',
    appId: '1:69956068335:ios:ba557e895e936e63cc4c1a',
    messagingSenderId: '69956068335',
    projectId: 'notes-b5858',
    storageBucket: 'notes-b5858.appspot.com',
    iosBundleId: 'com.mobileprogramming.klp5Mp.RunnerTests',
  );
}
